/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0d62f4d3676545c88ec8523213c055dd
title: Minecraft Diamond Axe
*/

import { useGLTF } from "@react-three/drei"
// @ts-ignore
import axeUrl from "../../../../assets/axe.glb"
import { GroupProps } from "@react-three/fiber"
import * as THREE from "three";
import { GLTF } from "three-stdlib";

interface GLTFResultWithAxe extends GLTF {
  nodes: {
    Mesh_1001_1: THREE.Mesh
    Mesh_1001_2: THREE.Mesh
  }
  materials: {
    material_2: THREE.Material
    material_3: THREE.Material
  }
}

export default function Axe(props: GroupProps): JSX.Element {
  const { nodes, materials } = useGLTF(axeUrl) as GLTFResultWithAxe
  return (
    <group dispose={null} {...props}>
      <group rotation={[0, Math.PI / 1.8, -0.3]} scale={0.5}>
        <mesh geometry={nodes.Mesh_1001_1.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Mesh_1001_2.geometry} material={materials.material_3} />
      </group>
    </group>
  )
}

useGLTF.preload(axeUrl)
